/*
 * This file is generated by jOOQ.
*/
package pl.sda.jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import pl.sda.jooq.Sda;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalculateSalaryByDept extends AbstractRoutine<BigDecimal> {

    private static final long serialVersionUID = 1029890682;

    /**
     * The parameter <code>sda.calculate_salary_by_dept.RETURN_VALUE</code>.
     */
    public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>sda.calculate_salary_by_dept.v_deptno</code>.
     */
    public static final Parameter<Integer> V_DEPTNO = createParameter("v_deptno", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public CalculateSalaryByDept() {
        super("calculate_salary_by_dept", Sda.SDA, org.jooq.impl.SQLDataType.NUMERIC);

        setReturnParameter(RETURN_VALUE);
        addInParameter(V_DEPTNO);
    }

    /**
     * Set the <code>v_deptno</code> parameter IN value to the routine
     */
    public void setVDeptno(Integer value) {
        setValue(V_DEPTNO, value);
    }

    /**
     * Set the <code>v_deptno</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setVDeptno(Field<Integer> field) {
        setField(V_DEPTNO, field);
    }
}
