/*
 * This file is generated by jOOQ.
*/
package pl.sda.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import pl.sda.jooq.tables.Dept;
import pl.sda.jooq.tables.Emp;
import pl.sda.jooq.tables.records.DeptRecord;
import pl.sda.jooq.tables.records.EmpRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>sda</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeptRecord> DEPT_PKEY = UniqueKeys0.DEPT_PKEY;
    public static final UniqueKey<EmpRecord> EMP_PKEY = UniqueKeys0.EMP_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmpRecord, DeptRecord> EMP__EMP_DEPT_FK = ForeignKeys0.EMP__EMP_DEPT_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DeptRecord> DEPT_PKEY = createUniqueKey(Dept.DEPT, "dept_pkey", Dept.DEPT.DEPTNO);
        public static final UniqueKey<EmpRecord> EMP_PKEY = createUniqueKey(Emp.EMP, "emp_pkey", Emp.EMP.EMPNO);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<EmpRecord, DeptRecord> EMP__EMP_DEPT_FK = createForeignKey(pl.sda.jooq.Keys.DEPT_PKEY, Emp.EMP, "emp__emp_dept_fk", Emp.EMP.DEPTNO);
    }
}
