/*
 * This file is generated by jOOQ.
*/
package pl.sda.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.sda.jooq.tables.Dept;
import pl.sda.jooq.tables.Emp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sda extends SchemaImpl {

    private static final long serialVersionUID = 980513356;

    /**
     * The reference instance of <code>sda</code>
     */
    public static final Sda SDA = new Sda();

    /**
     * The table <code>sda.dept</code>.
     */
    public final Dept DEPT = pl.sda.jooq.tables.Dept.DEPT;

    /**
     * The table <code>sda.emp</code>.
     */
    public final Emp EMP = pl.sda.jooq.tables.Emp.EMP;

    /**
     * No further instances allowed
     */
    private Sda() {
        super("sda", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Dept.DEPT,
            Emp.EMP);
    }
}
