/*
 * This file is generated by jOOQ.
*/
package pl.sda.jooq;


import javax.annotation.Generated;

import pl.sda.jooq.tables.Dept;
import pl.sda.jooq.tables.Emp;


/**
 * Convenience access to all tables in sda
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sda.dept</code>.
     */
    public static final Dept DEPT = pl.sda.jooq.tables.Dept.DEPT;

    /**
     * The table <code>sda.emp</code>.
     */
    public static final Emp EMP = pl.sda.jooq.tables.Emp.EMP;
}
